movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    # 메인 페이지
    path('', views.index, name='index'),
    # 리스트
    path('list/', views.list, name='list'),
    # 조회
    path('<int:pk>/', views.detail, name='detail'),
    # 생성    
    path('create/', views.create, name='create'),
    # 수정
    path('<int:pk>/update/', views.update, name='update'),
    # 삭제
    path('<int:pk>/delete/', views.delete, name='delete'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
]

movies/models.py
from django.db import models

# Create your models here.

class Review(models.Model):
    movie_name = models.CharField(max_length=20)
    title = models.CharField(max_length=20)
    content = models.TextField()
    grade = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['movie_name', 'title', 'content', 'grade']

movies/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm
# Create your views here.

def index(request):
    reviews = Review.objects.order_by('-created_at')[:6]
    return render(request, 'movies/index.html', {"reviews":reviews})

def list(request):
    reviews = Review.objects.all()
    return render(request, 'movies/list.html', {"reviews":reviews})

def detail(request, pk):
    review = Review.objects.get(pk=pk)

    return render(request, 'movies/detail.html', {"review":review})

def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            new_review = review_form.save()
            return redirect('movies:detail', pk=new_review.id)
    else:
        review_form = ReviewForm()
    return render(request, 'movies/create.html', {'review_form':review_form})

def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            new_review = review_form.save()
            return redirect('movies:detail', pk=new_review.id)
    else:
        review_form = ReviewForm(instance=review)
    return render(request, 'movies/create.html', {'review_form':review_form})

def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()
    return redirect('movies:index')

movies/templates/movies/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}게시글 작성하기{% endblock title %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}


{% block content %}
<div class="container mt-5">
<form method="post" class="form">
    {% csrf_token %}
  
    {% bootstrap_form review_form %}
    <div style="display: flex; justify-content: end; ">
        {% bootstrap_button button_type="submit" content="OK" button_class="btn-outline-dark" %}
        <div style="padding-left:1rem;">
            {% bootstrap_button button_type="reset" content="Cancel" button_class="btn-outline-dark"%}
        </div>
    </div>    
  </form>
</div>
{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}게시글{% endblock title %}

{% block content %}
  <div class="container my-5">
    <form>
      <div class="d-flex justify-content-between">
        <div class="">
          <label class="form-label fs-1">영화 제목</label>
        </div>
        <div class="d-flex" style="align-items: center; color: gray;">
          <p style="margin:0;">생성 날짜 : {{review.created_at }} | 수정 날짜 : {{ review.updated_at }}</p>
        </div>
      </div>
      <p class="fs-3">{{review.movie_name}}</p>

      <hr class="mt-5 mb-4">

      <div class="mb-3">
        <label class="form-label fs-1">리뷰 내용</label>
        <h1 class="form-control">
          <p style="font-weight: bold; margin: 0;">
            {{review.title}}<br> 
          </p>
          {{review.content}}
        </h1>
      </div>
    </form>

    <div class="my-4 d-flex justify-content-end">
      <button class="btn btn-outline-success button-link mx-1"><a href="{% url 'movies:update' review.pk %}" style="text-decoration:none; color:black;">수정</a></button>
      <button class="btn btn-outline-danger button-link mx-1"><a href="{% url 'movies:delete' review.pk %}" style="text-decoration:none; color:black;">삭제</a></button>
      <button class="btn btn-outline-secondary button-link mx-1"><a href="{% url 'movies:index' %}" style="text-decoration:none; color:black;">목록 페이지로</a></button>
    </div>
  </div>
{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'movies/css/index.css' %}">
{% endblock css %}


{% block content%}
<div style="height:30rem">
  <img src="{% static 'movies/images/review.png' %}" class="w-100 h-100">
</div>

<div style="display:flex; justify-content: center; align-items:center; flex-direction:column;">
<div class='title' style="display:flex; justify-content: center;">
<h2 style="background-color:rgb(255, 255, 202);">&nbsp 최근 리뷰보기 &nbsp</h2>
</div>
<div class="d-flex" style="justify-content:center; flex-wrap:wrap;">
{% for review in reviews %}
<div class="card" style="box-shadow:5px 5px 10px 5px rgba(211, 211, 211, 0.553)">
  <h5 class="card-header" style="font-weight:bold; background-color: rgba(2, 2, 2, 0.848); color:white">영화제목 [{{review.movie_name}}]</h5>
  <div class="card-body">
    <h5 class="card-title">{{review.title}}</h5>
    <p class="card-text">{{review.content}}</p>
    <div style="display:flex; justify-content:end">
    <a href="{% url 'movies:detail' review.pk %}" class="btn btn-outline-dark">더보기</a>
    </div>
  </div>
</div>

{% endfor %}
</div>
{% endblock content%}

movies/templates/movies/list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}모든 리뷰 보기{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'movies/css/index.css' %}">
{% endblock css %}

{% block content %}

<div style="display:flex; justify-content: center; align-items:center; flex-direction:column;">
  <div class='title' style="display:flex; justify-content: center;">
  <h2 style="background-color:rgb(255, 255, 202);">&nbsp 모든 리뷰보기 &nbsp</h2>
  </div>
  <div class="d-flex" style="justify-content:center; flex-wrap:wrap;">
  {% for review in reviews %}
  <div class="card" style="box-shadow:5px 5px 10px 5px rgba(211, 211, 211, 0.553)">
    <h5 class="card-header" style="font-weight:bold; background-color: rgba(2, 2, 2, 0.848); color:white">영화제목 [{{review.movie_name}}]</h5>
    <div class="card-body">
      <h5 class="card-title">{{review.title}}</h5>
      <p class="card-text">{{review.content}}</p>
      <div style="display:flex; justify-content:end">
      <a href="{% url 'movies:detail' review.pk %}" class="btn btn-outline-dark">더보기</a>
      </div>
    </div>
  </div>
  
  {% endfor %}

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'movies/images/purin.png' %}">
  {% block css %}
  {% endblock css %}
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <title>{% block title %}장성민 여다영 변규탁{% endblock title %}</title>
</head>
<body>
  <!--nav bar-->
  <nav class="navbar navbar-expand-lg sticky-top" style="background-color: white;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'movies:index' %}"><img src="{% static 'movies/images/duck.png' %}" style="width:2rem;"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'movies:create' %}">글쓰기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies:list' %}">리뷰보기</a>
          </li>

        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-dark" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}


  <!--footer-->
  <footer style="padding-top:2rem;">
    <div class="mt-5 d-flex justify-content-center align-items-center" style="height:3rem; background-color:black; width:100vw; position: sticky; bottom:0; ">
      <img src='{% static 'movies/images/dumble.png' %}' style="width:2rem;"><p class='px-3' style="margin:0; color:white;">All rights reserved. @Copyright by gyutak, seongmin, dayeong</p><img src='{% static 'movies/images/dumble.png' %}' style="width:2rem;">
    </div>
    
  </footer>
  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>